# Generated by Django 4.0.3 on 2022-04-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
