# Generated by Django 4.0.3 on 2022-04-05 01:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
